using System.IO;
using UnityEditor;
using UnityEngine;

namespace UniBridge.Editor
{
    public static class UniBridgeShareAndroidConfigurator
    {
        private const string ScanMarker = "UNIBRIDGE_UNIBRIDGESHARE_GENERATED"; // общая подстрока во всех форматах файлов

        // Androidlib for resources (Unity 6 requires .androidlib for res/)
        private const string LibDir                = "Assets/Plugins/Android/UniBridgeMobileKit/UniBridgeShareAndroid.androidlib";
        private const string LibManifestPath       = LibDir + "/AndroidManifest.xml";
        private const string ResXmlDir             = LibDir + "/res/xml";
        private const string FilePathsPath         = ResXmlDir + "/unibridgeshare_file_paths.xml";
        private const string BuildGradlePath       = LibDir + "/build.gradle";
        private const string ProjectPropertiesPath = LibDir + "/project.properties";

        // Legacy paths — for migration and cleanup
        private const string OldManifestDir = "Assets/Plugins/Android/UniBridgeShare"; // plain-dir подход (не работал)
        private const string OldResXmlFile  = "Assets/Plugins/Android/res/xml/unibridgeshare_file_paths.xml";
        private const string OldMainManifest = "Assets/Plugins/Android/AndroidManifest.xml"; // конфликтовал с Yandex

        // ── Public API ────────────────────────────────────────────────────────

        public static void Configure()
        {
            // Migration: delete the top-level manifest if generated by us (conflicts with Yandex SDK)
            if (File.Exists(OldMainManifest) && File.ReadAllText(OldMainManifest).Contains(ScanMarker))
            {
                File.Delete(OldMainManifest);
                FileUtil.DeleteFileOrDirectory(OldMainManifest + ".meta");
            }

            // Migration: delete the old plain-dir folder
            if (Directory.Exists(OldManifestDir))
            {
                FileUtil.DeleteFileOrDirectory(OldManifestDir);
                FileUtil.DeleteFileOrDirectory(OldManifestDir + ".meta");
            }

            // Migration: delete the old res/xml file (Unity 6 does not support plain res/)
            if (File.Exists(OldResXmlFile))
            {
                File.Delete(OldResXmlFile);
                FileUtil.DeleteFileOrDirectory(OldResXmlFile + ".meta");
            }

            // Androidlib — XML resource only, for FileProvider
            // <provider> is injected into the generated manifest via UniBridgeShareAndroidManifestInjector
            if (!Directory.Exists(LibDir))
                Directory.CreateDirectory(LibDir);
            if (!Directory.Exists(ResXmlDir))
                Directory.CreateDirectory(ResXmlDir);

            WriteFileIfSafe(FilePathsPath,   FilePathsTemplate,   ScanMarker);
            WriteFileIfSafe(BuildGradlePath, BuildGradleTemplate, ScanMarker);
            File.WriteAllText(LibManifestPath,       LibMinimalManifestTemplate);
            File.WriteAllText(ProjectPropertiesPath, ProjectPropertiesTemplate);

            AssetDatabase.Refresh();
            Debug.Log("[UniBridge] UniBridgeShare Android resource files configured.");
        }

        public static void Cleanup()
        {
            // Delete androidlib (resources)
            if (Directory.Exists(LibDir))
            {
                if (!File.Exists(BuildGradlePath) || File.ReadAllText(BuildGradlePath).Contains(ScanMarker))
                {
                    FileUtil.DeleteFileOrDirectory(LibDir);
                    FileUtil.DeleteFileOrDirectory(LibDir + ".meta");
                }
                else
                    Debug.LogWarning("[UniBridge] Skipping 'UniBridgeShareAndroid.androidlib/' — not generated by UniBridge.");
            }

            // Delete old plain-dir folder
            if (Directory.Exists(OldManifestDir))
            {
                FileUtil.DeleteFileOrDirectory(OldManifestDir);
                FileUtil.DeleteFileOrDirectory(OldManifestDir + ".meta");
            }

            // Delete our top-level manifest if we generated it
            if (File.Exists(OldMainManifest) && File.ReadAllText(OldMainManifest).Contains(ScanMarker))
            {
                File.Delete(OldMainManifest);
                FileUtil.DeleteFileOrDirectory(OldMainManifest + ".meta");
            }

            // Delete old res/xml file
            if (File.Exists(OldResXmlFile))
            {
                File.Delete(OldResXmlFile);
                FileUtil.DeleteFileOrDirectory(OldResXmlFile + ".meta");
            }

            AssetDatabase.Refresh();
            Debug.Log("[UniBridge] UniBridgeShare Android resource files removed.");
        }

        public static bool IsConfigured() => File.Exists(FilePathsPath);

        [InitializeOnLoadMethod]
        private static void EnsureConfiguredOnLoad()
        {
            if (EditorUserBuildSettings.selectedBuildTargetGroup != BuildTargetGroup.Android) return;
            var config = UnityEngine.Resources.Load<UnityEngine.Object>("UniBridgeShareConfig");
            var shareAdapter = config != null
                ? new SerializedObject(config).FindProperty("PreferredShareAdapter")?.stringValue ?? ""
                : "";
            if (shareAdapter != "UNIBRIDGESHARE_ANDROID") return;
            if (!IsConfigured())
                Configure();
        }

        // ── File helpers ──────────────────────────────────────────────────────

        private static void WriteFileIfSafe(string path, string content, string marker)
        {
            if (File.Exists(path) && !File.ReadAllText(path).Contains(marker))
            {
                Debug.LogWarning($"[UniBridge] Skipping '{path}' — not generated by UniBridge.");
                return;
            }

            File.WriteAllText(path, content);
        }

        // ── Templates ─────────────────────────────────────────────────────────

        // Minimal manifest for androidlib (no <provider> — injected via IPostGenerateGradleAndroidProject)
        private const string LibMinimalManifestTemplate =
@"<?xml version=""1.0"" encoding=""utf-8""?>
<!-- UNIBRIDGE_UNIBRIDGESHARE_GENERATED -->
<manifest xmlns:android=""http://schemas.android.com/apk/res/android"" />
";

        private const string FilePathsTemplate =
@"<?xml version=""1.0"" encoding=""utf-8""?>
<!-- UNIBRIDGE_UNIBRIDGESHARE_GENERATED -->
<paths>
    <cache-path name=""unibridgeshare"" path=""."" />
</paths>
";

        private const string ProjectPropertiesTemplate = "target=android-9\nandroid.library=true\n";

        private const string BuildGradleTemplate =
@"// UNIBRIDGE_UNIBRIDGESHARE_GENERATED
apply plugin: 'com.android.library'

android {
    namespace 'com.unibridge.share'
    compileSdkVersion 34
    buildToolsVersion '34.0.0'

    defaultConfig {
        minSdkVersion 21
    }

    buildFeatures {
        buildConfig false
    }
}
";
    }
}
